# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 069d49f96f54630c850edbcdeaa5e43ae423f08bcb7ec39284746bb8a7d306c8a931f881f9467daa8db531d6c096a4ee465a7032181b89b738ef96e7e5837f20

test:
  secret_key_base: b93c48b92baef6aa99d525c789a63abea41b3f1bb47f873a8e1056c68075514e1e0fa06f7286fc72e9ea5cd53dad450b8ac3da968aba2793b263d1aad9175a54

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
